### ISSUE TITLE
런타임 퍼미션 처리 버그

### ISSUE THREAD

**Issue by kklyoon** [Charlezz/Pickle#1]
런타임 권한 처리관련 버그 있습니다.

### 재현과정
1. 시스템 설정에서 피클의 저장소 권한을 취소한다.
2. 피클 샘플앱을 실행한다. 
3. 두버튼 중 아무거나 누른다.
4. 런타임 권한 요청에서 Allow 를 선택한다.
5. 사진 리스트가 떠야하는데 아무것도 뜨지 않는다.

**Comment by Charlezz** [comment]
감사합니다. 다음 버전 릴리즈 할 때 처리 할게요!

**Comment by Charlezz** [comment]
beta01에서 해결했습니다.
