### ISSUE TITLE
썸네일 업데이트 버그

### ISSUE THREAD

**Issue by kklyoon** [Charlezz/Pickle#3]
### 증상재현

- 피클에서 썸네일 리스트를 확인한다.
- 기본사진앱이나 다른 앱으로 사진에 낙서를 한다.
- 다시 피클앱을 열어서 썸네일을 확인한다.
- 낙서된 사진의 썸네일이 업데이트 되어 있지 않다.

**Comment by Charlezz** [comment]
제보 감사합니다. ContentsObserver 추가하도록 할게요!

**Comment by kklyoon** [comment]
저는 Glide 옵션에서 signature 항목에 해쉬로 쓸만한걸 넣어주니 잘되더라구요
https://medium.com/android-news/best-strategy-to-load-images-using-glide-image-loading-library-for-android-e2b6ba9f75b2
요글 참고했습니다!

**Comment by Charlezz** [comment]
알려주신 내용 참고해서 28b2340 에서 수정했습니다!
